#!/bin/bash

#
# Script to remove data from the PostgreSQL and Elasticsearch
# data stores. For testing purposes only.
#

# Remove the data from the Postgres topic map tables
psql -U tq_admin -W -h 127.0.0.1 -a -f cleandb.sql tq_database

# Remove the data from Elasticsearch
curl -XDELETE localhost:9200/topics
